---
title: Using Scagnostics to find Interesting Projections of Multivariate Data

# to produce blinded version set to 1
blinded: 0

authors: 
- name: Ursula Laa
  thanks: The authors gratefully acknowledge the support of the Australian Research Council
  affiliation: Department of Physics, Monash University
  email: \email{ursula.laa@monash.edu}
  
- name: Dianne Cook
  affiliation: Department of Econometrics and Business Statistics, Monash University
  
- name: Heike Hofmann
  affiliation: Department of Statistics, Iowa State University
  
- name: Hadley Wickham
  affiliation: RStudio
  
- name: Antony Unwin
  affiliation: Department of Mathematics, Augsburg University
  
- name: Katrin Grimm
  affiliation: ???

keywords:
- tour
- projection pursuit 
- statistical graphics
- data visualisation
- exploratory data analysis
- high-dimensional data

abstract: |
  Projection pursuit describes a procedure for searching high-dimensional data for "interesting" low-dimensional projections via the optimization of a criterion function called the projection pursuit index. Most indexes developed focus on finding projections with cluster structure, outliers, or separations between known groups. Here, we are interested in finding projections where the shapes are odd, or where known groups have different shapes despite having the same mean and variance. The new indexes are based on scagnostics, which were originally developed to choose pairs of interesting variables from a large collection. An examination of the properties of the scagnostics is included, and code in the form of an R package is provided.  

bibliography: bibliography.bib
output: rticles::asa_article
---

# Introduction

The term "projection pursuit" was coined by @ff74 to describe a procedure for searching high-(say $p$)dimensional data for "interesting" low- dimensional projections ($k=1$ or $2$ usually). The procedure, originally suggested by @kr69, involves defining a criterion function, or index, that measures the "interestingness" of each $k$-dimensional projection of $p$-dimensional data. This criterion function is optimized over the space of all $k$-dimensional projections of $p$-space, searching for both global and local maxima. It is hoped that the resulting solutions reveal low-dimensional structure in the data not necessarily found by methods such as principal component analysis.

A large number of projection pursuit indices have been developed [@f87] [@CBC92] [@Lee05] [@AHC02] [@CEM:CEM2568] [@JS87] [@5508437]. Many of these are developed to detect departure from multivariate normal, which includes clusters or outliers, or nonlinearity. Some have been developed to detect separations between known groups. However, if one wants to find unusual shapes, or shape differences between groups there are no options. One reason, is that it is hard, because defining what is meant by shape is not straightforward. An approach that seems plausible begins with scagnostics, developed by @scag, and explored in @WW08. 

*** Motivating example ??

Scagnostics are scatterplot diagnostics. They were primarily developed to extract pairs of interesting variables from a large collection. XXX (Ursula to fill in based loosely on material at the German language wikipedia page - it would be good to translate this page and provide an English version on wikipedia). Scagnostics are available in two R packages @LWscagR and @HWscagR. This work is built upon the scagnostics package by @HWscagR because the underlying base is built using C, works across platforms. 

A projection pursuit index, a function of all possible projections of the data, invariably has many "hills and valleys" and "knife-edge ridges" because of the varying shapes in the underlying density of observations from one projection to the next. From an exploratory data analysis perpective it is interesting to combine numerical optimisation with visualisation to watch the structure of the data moving into a maximum, to jump away from this projection and follow the optimisation again, invariably moving from local maxima to local maxima, and perhaps even a global maximum. Each of these maxima can reveal different information about the data. Projection pursuit optimisation combined with geodesic interpolations between projections provided by a tour [@As85], is called a projection pursuit guided tour [@CBCH94]. Software to run a projection pursuit guided tour is available in the R package, "tourr" [@tourr].

The paper investigates the nature of scagnostics, particularly when considered as candidates for projection pursuit indices (Section \ref{sec:investigate})). It develops indexes for finding shapes as defined by the scagnostics, and for finding different shapes between multiple groups (Section \ref{sec:indexes}). Changes to the optimisation of the projection pursuit guided tour were needed to accommodate some of the complexities of the scagnostic indexes. The new guided tour methods are applied to contemporary problems from paarticle physics (Section \ref{sec:phys}). The paper is accompanied by the R package "binostics" available on CRAN, and the new indices have been implemented in the "tourr" package. 

# Investigation of scagnostics
\label{sec:investigate}

## Scagnostic discreteness

*** temporal trace of scagnostics showing discreteness, with projections illustrating little difference

*** katrin's work

## Speed

# Modification to scagnostics

## Smoothing

## Jittering

## Tour optimisation

# Scagnostics indices
\label{sec:indexes}

## Individual 

## Two group differences

## Multiple group differences

# Application to particle physics data
\label{sec:phys}

## Data description

## Software setup

## Scagnostics of grand tour projections

# Discussion

# References
