## Author's response to reviews

The authors wish to thank the reviewers for the careful reading and comments on our first version. This is the detailed information on how we have addressed each comment from the reviewers.

### Associate Editor:

The submission has been evaluated by two reviewers. The manuscript is well written and organized. I have some more philosophical issues in addition to those raised by the two reviewers.

The authors need to convince readers (users) this kind of environment is good for daily EDA for the real world of big data/data science.

**We have added a paragraph to the introduction to explain the approach for higher dimensional problems, as follows:** 

**PP can also be used to explore data with many more variables, data that is commonly seen today. For example, [@Cook:2018mvr] explores a 56-dimensional parameter space, by first reducing the number of dimensions to the first six principal components, before applying projection pursuit. There is not a single solution for working with high-dimensional data. PCA was appropriate for this problem because reducing to principal component space removed the linear dependencies but preserved the nonlinear relationships that were interesting to discover. Some projection pursuit indexes incorporation penalty terms to naturally deal with noise dimensions. Having an efficient optimizer can also important with increasing dimensionality, because there are many more dimensions to search.**

Example(s) with very large number (at least hundreds) of dimensions should be included in the study.

**The simulation study and the applications reveal that the current methods are efficient only in smaller parameter spaces. There are several components that would be required to scale it to examples with hundreds of dimensions: (1) fast computational engine, (2) an efficient optimiser, (3) new PP indexes that effectively use penalty terms to automatically elliminate nuisance dimensions. The first two would require major implementation work. The methods explained in this paper would be useful for assessing and evaluating new PP indexes. The recommended approach to high-dimensions is to first reduce the dimensionality using PCA, before applying PP. We have explained a sentence to this effect in the discussion section.** 

Who are the target users of this environment? Do you recommend naive users (users without much EDA experience) to get hand on the proposed system?

How do you encourage users to try your system?

**The target audience consists of two groups. First we hope that researchers developing new index functions, who will find our methods useful to diagnose their new indexes. We have implemented out methods in the R package, spinebil, to make this an attractive prospect to other researchers. The second group would be people interested in applying the indexes to explore nonlinear structure in their data. This can be done directly using the guided tour, in the tourr package, using code similarly to that distributed with this paper. We also encourage novice R users to try this through the tour GUI available in the galahr package. Both packages are now referenced in the discussion.** 

**The considered index functions are all available in R packages, which makes them readily available to all. The packages are mbgraphics, binostics and minerva, which are now updated and on CRAN.**

### Reviewer #1: 

Review report for "Using tours to visually investigate properties of new projection pursuit indexes with application to problems in physics"

This manuscript presented a simulation study to visually explore the properties of a set of projection pursuit indexes (PPIs) using a grand tour based on the five criterions. The selected PPIs were then applied to two real datasets in physics for revealing potential patterns. In general I found this article was well written and it fully addresses the problems to be solved. I have no major issue. Some specific comments are listed below:

1) Authors conducted the simulation study to evaluate the selected PPIs based on the five criterions and the results were summarized into Table 3. On the other hand, authors may consider another table that summarizes the advantages/disadvantages/characteristics of these mathematical indexes from the previous literatures. This review is helpful for users to comprehend these indexes' properties.

**This comparison was the subject of the thesis Grimm (2016). We have now added a brief summary of these findings at the end of section 2.2.**

2) According to the aims & scope of the journal, Computational Statistics, this article should keep the content and discussion relevant more focused on the computational aspects.

**We are really not sure what is being requested here. We have tried to focus the content in the paper on the compututational aspects of the work, and have kept it concise and to the point. The paper is at a reasonable length. The appendix has some details that broaden the discussion. If there are more parts that the reviewer suggests should be shifted to an appendix, we would be happy to do that.**

3) Although the target of this article focuses on the dataset with two-dimensional structure (d=2), it is worth to discuss the possibility (or give some suggestions) of applying the proposed procedure to the situation where d > 2.

**We thank the referee for the suggestion. Many of the available index functions also work for d>2, for example the ones in the tourr package work for arbitrary dimension. The work in this paper focuses on studying a selection of indexes designed for 2D. However, the same diagnostics could be applied generally to any dimension projection index. We have commented on this in the discussion.**

4) The procedure for assessing the PPIs' properties was listed in Section 3.1.2. In addition, it would be helpful to list the procedure step-by-step (with the detailed R functions/packages) to guide the users how to apply the tour methodology with PPIs to explore the potential patterns of the real-world datasets. 

**As we now mention in the discussion, the easiest way for new users is to access these through the graphical interface available in the galahr package. The package documentation includes a step-by-step example using the guided tour. We have also added a short guide to applications (Section 4.3).** XXX check! 

5) Why use the 5th/95th percentiles in Table 2 instead of the average/sd?

**The main reason is that it provides a range of typical values of the index, which is useful for scaling the index dynamically in the guided tour. While it is possible to use a mean, and maybe +/- 3sd's, its possible that extreme values could occur making it less useful to scale the index for comparison  to other indexes.**

6) There was some confusion regarding the number of PPIs used in the content. There are eight indexes in Table 2; nine indexes in Fig 7; six indexes in Table 3, and seven indices in Section 4.2.2.

**We are considering seven new index functions. In Section 3, we also include the holes index for comparison, because it is an established index with generally good, focused performance. This is now explained in the end of Section 2.2. The holes index is not included in Table 3 because the focus is on summarising our findings on the new index functions. Because the MINE indexes (MIC, TIC) that have very similar behaviour in all assessments,  we combined for this summary. We have now added another line for TIC, because it doesn't use much extra space, and saves confusion about the differing number of indexes. Finally Section 4.2.2 applies a selection of the new index functions to physics problems.**

7) I would suggest moving the appendix A (the description of "holes/cmass" index) to Section 2.2 for readability.

**We now briefly describe the holes index and relevant references in Section 2.2. However, the explanation of the rescaling should remain in the appendix, because it distracts from the main message of Section 2.2.**

8) Check the spelling of words for clarity and consistency, e.g, splines2D/splines2d; convex/1-convex, MIC/MICe, and so on.

**We have made the spelling consistent where referring to the same index, and provided explanations where the different spelling indicates differences in index calculation.**

### Reviewer #2:

Summary of the contribution:
The authors present a simulation study to evaluate various projection pursuit indexes for detecting specific bivariate patterns in the data. Moreover, two data sets from physics are examined using PPI.

Major remarks
The simulation study targets three particular structures the pipe, the sine, and the spiral. Some motivation and justification for selecting these structures should be added.

 **We have added more explanation in Section 3.1.1 outlining the motivation for why these three structures are interesting for the simulation study.**

Second, the simulation study uses six-dimensional data of which four dimensions contribute nuisance and the other two the intended structure. Implicitly, this is clear, but the description does not make this explicit and uses the general notion of p dimensions instead. Please make this more explicit and also provide some justification that this set-up is adequate for targeting the problem at hand.

**We have added an explicit statement that we fix p=6. As mentioned in the statement p=6 results in two independent planes showing the nuisance distribution and one plane showing the structured distribution. This set-up is adequate for most of our study where we follow interpolated paths either between nuisance only projections or from nuisance views to structured projections.**

Thirdly, the simulations refer to sequences of projections (the horizontal axis in plots in Figures 2, 3, and 4. As I understand these sequences are a consequence of optimising the corresponding projection pursuit index. How can you then actually control the two different scenarios referred to in section 3.2 and 3.3? Or, do you extract a specified sequence of projections? Moreover, how do you make sure that you have the same sequence length for each trial? Please clarify!

**Captions and the text in Sections 3.2-3 have been changed to make it clearer that Figures 2 and 3 present the trace for a specified sequence of projections (since in the simulation study the nuisance and structured views are known), and Figure 4 is different as in this case the path is indeed the result of optimising an index.**


The optimisation methods are further discussed in section 3.4 and depend on the structure present in the data. What is the value of these investigations for more realistic settings in which the structure is not known.

**It is important to understand the performance of the optimisation before applying the method on new examples and we use the known examples for this. This is now explained in the first sentence in Section 3.4.** XXX check

Finally, the relationship between the simulation study and the examples using the astrophysics data remains unclear. How are the physics applications linked to the simulation study and vice versa? Currently, the two aspects seem to me rather independent and could actually be presented in separate manuscripts. Moreover, since some rather important aspects of the simulation study have been put into an appendix. For the COST audience certainly the details of the simulation study are more relevant than the astrophysics application.

**(Point to initial motiviation, maybe say that physics application presents more realistic example with interesting structures in non-trivial projections)** XXX add

Minor remarks
When introducing the various PPIs some terms and notations are used which are not properly introduced, e.g. alpha hull, convex. Check which ones actually need to be properly defined as they are needed for further steps and for which ones you could just refer to the literature avoiding unnecessary details.

**Suggestion: explain alpha hull, convex hull, MST, and add reference for smoothing splines?** XXX decide and add

In Figure 3, each plot shows a vertical blue line. Please explain what this line represents.

**We have added such a sentence to the figure caption.**

p. 14, l. 26: optimist should be optimise

**We have fixed the typo.**